<a href="https://colab.research.google.com/github/sahoop2002/PLOTLY/blob/main/PRATIP_Session_on_Plotly_Graph_Objects_(go).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Introduction to Plotly


*  Untill now we did visualizations using Matplotlib, Seaborn, and Pandas. All of them produce static image files.
* Plotly is company based out in Canada famous for it's products like Plotly and Dash.
* Plotly creates interactive visualizations in the form of HTML files.
* Drawback of Plotly - can't work with a live data source.
* Dash is used to create live data based dashboards.

In [ ]:
import numpy as np
import pandas as pd
import plotly.offline as pyo
import plotly.graph_objs as go

import plotly.io as pio
pio.renderers.default = 'colab'

In [ ]:
match = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')

In [ ]:
ipl = delivery.merge(match, left_on='match_id', right_on='id')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [ ]:
# Scatter plots are drawn between two continuous variables.
# Problem : We are going to draw a scatter plot between Batsman Avg(X axis) and Batsman Strike Rate(Y axis) of the top 50 batsman in IPL(All time)

In [ ]:
# Avg vs SR group of Top 50 batsman(in terms of total runs)
# Fetching a new dataframe with top 50 batsman

top50 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(50).index.tolist()
new_ipl = ipl[ipl['batsman'].isin(top50)]

In [ ]:
# Calculating SR
# SR = [(number of runs scored) / (number of balls played)]*100
runs = new_ipl.groupby('batsman')['batsman_runs'].sum()
balls = new_ipl.groupby('batsman')['batsman_runs'].count()
sr = (runs/balls)*100
sr = sr.reset_index()
sr

             batsman  batsman_runs
0     AB de Villiers    145.129059
1       AC Gilchrist    133.054662
2           AJ Finch    126.299213
3          AM Rahane    117.486549
4          AT Rayudu    123.014257
5        BB McCullum    126.318203
6           BJ Hodge    121.422376
7           CH Gayle    144.194313
8          DA Miller    137.709251
9          DA Warner    138.318401
10          DJ Bravo    122.286822
11         DJ Hussey    120.072661
12  DPMD Jayawardene    118.791064
13          DR Smith    132.279534
14      F du Plessis    124.161074
15         G Gambhir    120.361200
16        GJ Maxwell    157.564103
17         JH Kallis    105.936272
18         JP Duminy    121.970624
19        KA Pollard    140.621266
20     KC Sangakkara    118.469101
21        KD Karthik    123.008475
22           KK Nair    124.650161
23           M Vijay    120.028681
24        MEK Hussey    119.963592
25         MK Pandey    116.938453
26         MK Tiwary    114.127424
27          MS Dhoni    132.835821
28           NV Ojha    114.528024
29          PA Patel    112.718447
30          R Dravid    113.347237
31         RA Jadeja    118.792867
32         RG Sharma    128.497251
33        RV Uthappa    127.635135
34       S Badrinath    115.742972
35          S Dhawan    118.502496
36        SC Ganguly    101.734540
37          SE Marsh    130.109775
38          SK Raina    134.995548
39         SPD Smith    128.507127
40      SR Tendulkar    114.187867
41         SR Watson    134.838379
42         SS Tiwary    114.851485
43         SV Samson    122.403433
44        TM Dilshan    110.124164
45           V Kohli    126.588437
46          V Sehwag    148.827059
47           WP Saha    127.727646
48         YK Pathan    140.751445
49      Yuvraj Singh    126.390244

In [ ]:
# calsulating Avg
# Avg = (Total number of Runs) / (Number of outs)
# Calculating number of top 50 batsman

out = ipl[ipl['player_dismissed'].isin(top50)]
nouts = out['player_dismissed'].value_counts()
avg = runs/nouts

avg = avg.reset_index()
avg.rename(columns={'index':'batsman',0:'avg'},inplace = True)

avg = avg.merge(sr, on='batsman')
avg

             batsman        avg  batsman_runs
0     AB de Villiers  38.307692    145.129059
1       AC Gilchrist  27.223684    133.054662
2           AJ Finch  27.186441    126.299213
3          AM Rahane  33.593407    117.486549
4          AT Rayudu  27.146067    123.014257
5        BB McCullum  28.112245    126.318203
6           BJ Hodge  33.333333    121.422376
7           CH Gayle  41.022472    144.194313
8          DA Miller  34.733333    137.709251
9          DA Warner  40.140000    138.318401
10          DJ Bravo  22.945455    122.286822
11         DJ Hussey  26.979592    120.072661
12  DPMD Jayawardene  28.250000    118.791064
13          DR Smith  28.392857    132.279534
14      F du Plessis  30.116279    124.161074
15         G Gambhir  31.541985    120.361200
16        GJ Maxwell  25.081633    157.564103
17         JH Kallis  28.552941    105.936272
18         JP Duminy  39.860000    121.970624
19        KA Pollard  28.707317    140.621266
20     KC Sangakkara  25.953846    118.469101
21        KD Karthik  24.811966    123.008475
22           KK Nair  25.173913    124.650161
23           M Vijay  26.431579    120.028681
24        MEK Hussey  38.764706    119.963592
25         MK Pandey  28.500000    116.938453
26         MK Tiwary  29.428571    114.127424
27          MS Dhoni  37.872340    132.835821
28           NV Ojha  20.986486    114.528024
29          PA Patel  21.700935    112.718447
30          R Dravid  28.233766    113.347237
31         RA Jadeja  24.055556    118.792867
32         RG Sharma  32.612403    128.497251
33        RV Uthappa  29.515625    127.635135
34       S Badrinath  30.659574    115.742972
35          S Dhawan  32.669725    118.502496
36        SC Ganguly  25.452830    101.734540
37          SE Marsh  39.507937    130.109775
38          SK Raina  33.940299    134.995548
39         SPD Smith  37.239130    128.507127
40      SR Tendulkar  33.826087    114.187867
41         SR Watson  30.917647    134.838379
42         SS Tiwary  28.355556    114.851485
43         SV Samson  25.464286    122.403433
44        TM Dilshan  26.813953    110.124164
45           V Kohli  37.483051    126.588437
46          V Sehwag  27.555556    148.827059
47           WP Saha  25.524590    127.727646
48         YK Pathan  29.816327    140.751445
49      Yuvraj Singh  25.653465    126.390244

In [ ]:
# plot scatter plot here

trace = go.Scatter(x=avg['avg'], y=avg['batsman_runs'], mode='markers',text = avg['batsman'], marker = {'color': 'red', 'size': 12})
data = [trace]

layout = go.Layout(title='Batsman Avg vs SR, Top 50 Innings',
                   xaxis={'title':'Batsman Average'},
                   yaxis={'title':'Batsman Strike Rate'})

fig = go.Figure(data=data, layout=layout)
fig.show()

In [ ]:
# plot line chart
# year by year batsman performance

single = ipl[ipl['batsman']=='AB de Villiers']
performance = single.groupby('season')['batsman_runs'].sum().reset_index()
performance

   season  batsman_runs
0    2008            95
1    2009           465
2    2010           111
3    2011           312
4    2012           319
5    2013           373
6    2014           395
7    2015           513
8    2016           687
9    2017           216

In [ ]:
# plot line chart here

trace = go.Scatter(x=performance['season'], y=performance['batsman_runs'], mode='lines+markers',marker = {'color': 'red', 'size': 12})
data = [trace]

layout = go.Layout(title = 'Year by Year Performance',
                   xaxis = {'title':'Season'},
                   yaxis = {'title':'Total Runs'})
fig = go.Figure(data = data, layout = layout)

fig.show()

In [ ]:
single1 = ipl[ipl['batsman']=='V Kohli']
performance1 = single1.groupby('season')['batsman_runs'].sum().reset_index()
performance1

single2 = ipl[ipl['batsman']=='MS Dhoni']
performance2 = single2.groupby('season')['batsman_runs'].sum().reset_index()
performance2

   season  batsman_runs
0    2008           414
1    2009           332
2    2010           287
3    2011           392
4    2012           357
5    2013           461
6    2014           371
7    2015           372
8    2016           284
9    2017           290

In [ ]:
trace1 = go.Scatter(x=performance['season'], y=performance1['batsman_runs'], mode='lines+markers',marker = {'color': 'red', 'size': 12},name = 'V Kohli')
data = [trace]

trace2 = go.Scatter(x=performance['season'], y=performance2['batsman_runs'], mode='lines+markers',marker = {'color': 'blue', 'size': 12}, name = 'MS Dhoni')
data = [trace1,trace2]

layout = go.Layout(title = 'Year by Year Performance',
                   xaxis = {'title':'Season'},
                   yaxis = {'title':'Total Runs'})
fig = go.Figure(data = data, layout = layout)

fig.show()

In [ ]:
# multiple line charts
def batsman_comp(*name):
  data = []
  for i in name:
    single = ipl[ipl['batsman']==i]
    performance = single.groupby('season')['batsman_runs'].sum().reset_index()

    trace = go.Scatter(x=performance['season'], y=performance['batsman_runs'],mode = 'lines+markers',name = i)
    data.append(trace)

  layout = go.Layout(title = 'Batsman Record Comparison',
                     xaxis = {'title':'Season'},
                     yaxis = {'title':'Total Runs'})
  fig = go.Figure(data = data, layout = layout)
  fig.show()

In [ ]:
batsman_comp('V Kohli', 'RG Sharma', 'DA Warner', 'MS Dhoni')

In [ ]:
# bar plot

top10 = ipl.groupby('batsman')['batsman_runs'].sum().sort_values(ascending=False).head(10).index.tolist()
top10_df = ipl[ipl['batsman'].isin(top10)]

In [ ]:
top10_score = top10_df.groupby('batsman')['batsman_runs'].sum().reset_index()
top10_score

          batsman  batsman_runs
0  AB de Villiers          3486
1        CH Gayle          3651
2       DA Warner          4014
3       G Gambhir          4132
4        MS Dhoni          3560
5       RG Sharma          4207
6      RV Uthappa          3778
7        S Dhawan          3561
8        SK Raina          4548
9         V Kohli          4423

In [ ]:
# plot bar graph here
trace = go.Bar(x=top10_score['batsman'], y=top10_score['batsman_runs'])
data = [trace]
layout = go.Layout(title = 'Top 10 IPL batsman',
                   xaxis = {'title':'Batsman'},
                   yaxis = {'title':'Total Runs'})
fig = go.Figure(data = data, layout = layout)
fig.show()

#**There are three types of Bar Graphs**
* Nested Bar Graph
* Stacked Bar Graph
* Overlayed Bar Graph

In [ ]:
from typing_extensions import final
iw = top10_df.groupby(['batsman','inning'])['batsman_runs'].sum().reset_index()
mask = iw['inning']==1
mask2 = iw['inning']==2
one = iw[mask].copy()
two = iw[mask2].copy()

one.rename(columns={'batsman_runs':'1st innings'},inplace=True)
two.rename(columns={'batsman_runs':'2nd innings'},inplace=True)

final = one.merge(two, on='batsman')[['batsman','1st innings','2nd innings']]
final

          batsman  1st innings  2nd innings
0  AB de Villiers         2128         1345
1        CH Gayle         2003         1623
2       DA Warner         2118         1896
3       G Gambhir         1699         2433
4        MS Dhoni         2232         1328
5       RG Sharma         2344         1863
6      RV Uthappa         1516         2262
7        S Dhawan         2262         1299
8        SK Raina         2647         1893
9         V Kohli         2391         2027

In [ ]:
trace1 = go.Bar(x=final['batsman'], y=final['1st innings'],name = '1st innings',marker ={'color':'crimson'})
trace2 = go.Bar(x=final['batsman'], y=final['2nd innings'],name = '2st innings',marker ={'color':'cornflowerblue'})
data = [trace1,trace2]

layout = go.Layout(title = 'Inning wise Scores',
                   xaxis = {'title':'Batsman'},
                   yaxis = {'title':'Total Runs'},
                   barmode = 'overlay')
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
trace1 = go.Bar(x=final['batsman'], y=final['1st innings'],name = '1st innings',marker ={'color':'crimson'})
trace2 = go.Bar(x=final['batsman'], y=final['2nd innings'],name = '2st innings',marker ={'color':'cornflowerblue'})
data = [trace1,trace2]

layout = go.Layout(title = 'Inning wise Scores',
                   xaxis = {'title':'Batsman'},
                   yaxis = {'title':'Total Runs'})
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
# bubble plot
new_ipl= new_ipl[new_ipl['batsman_runs']==6]

six = new_ipl.groupby('batsman')['batsman_runs'].count().reset_index()
x = avg.merge(six, on='batsman')
trace = go.Scatter(x=x['avg'],y=x['batsman_runs_x'],mode='markers',marker={'size':x['batsman_runs_y']},text = x['batsman'])
data = [trace]
layout = go.Layout(title='Bubble Chart',
                   xaxis={'title':'Batsman Average'},
                   yaxis={'title':'Batsman Strike Rate'})
fig = go.Figure(data=data, layout=layout)
fig.show()

In [ ]:
# box plot
match_agg = delivery.groupby(['match_id'])['total_runs'].sum().reset_index()
season_wise = match_agg.merge(match, left_on='match_id', right_on='id')[['match_id','total_runs','season']]
season_wise

     match_id  total_runs  season
0           1         379    2017
1           2         371    2017
2           3         367    2017
3           4         327    2017
4           5         299    2017
..        ...         ...     ...
631       632         277    2016
632       633         317    2016
633       634         302    2016
634       635         325    2016
635       636         408    2016

[636 rows x 3 columns]

In [ ]:
trace = go.Box(x=season_wise['total_runs'],name = 'All Seasons',marker ={'color':'green'})
data = [trace]
layout = go.Layout(title = 'Total Score Analysis',
                   xaxis = {'title':'Total Score'})
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
# two box plot together

trace1 = go.Box(x=season_wise[season_wise['season']==2017]['total_runs'],name = '2017',marker ={'color':'red'})
trace2 = go.Box(x=season_wise[season_wise['season']==2008]['total_runs'],name = '2008',marker ={'color':'green'})

data = [trace1,trace2]
layout = go.Layout(title = 'Total Score Analysis',
                   xaxis = {'title':'Total Score'})
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
# plot Distplot

import plotly.figure_factory as ff


hist_data = [avg['avg']]
group_labels = ['Average']

fig = ff.create_distplot(hist_data, group_labels)
fig.show()

In [ ]:
hist_data = [avg['avg'],avg['batsman_runs']]
group_labels = ['Average','Strike Rate']

fig = ff.create_distplot(hist_data, group_labels,bin_size = [5,10])
fig.show()

In [ ]:
# plot Histogram

x = delivery.groupby('batsman')['batsman_runs'].count()>150
x = x[x].index.tolist()

new = delivery[delivery['batsman'].isin(x)]

runs = new.groupby('batsman')['batsman_runs'].sum()
balls = new.groupby('batsman')['batsman_runs'].count()

sr = (runs/balls)*100
sr= sr.reset_index()
sr

             batsman  batsman_runs
0     A Ashish Reddy    142.857143
1           A Mishra     89.756098
2          A Symonds    124.711908
3    AA Jhunjhunwala     99.541284
4         AB Agarkar    111.875000
..               ...           ...
169          Y Nagar    105.166052
170  Y Venugopal Rao    113.872832
171        YK Pathan    138.860326
172      YV Takawale    104.918033
173     Yuvraj Singh    125.283190

[174 rows x 2 columns]

In [ ]:
# plot histogram

trace = go.Histogram(x=sr['batsman_runs'],name = 'Strike Rate variations',xbins = {'size':3})

data = [trace]
layout = go.Layout(title = 'Strike Rate Analysis',
                   xaxis = {'title':'Strike Rate'},
                   yaxis = {'title':'Player Count'})
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
# plot histogram

trace = go.Histogram(x=sr['batsman_runs'],name = 'Strike Rate variations',xbins = {'size':3,'start': 20,'end': 100})

data = [trace]
layout = go.Layout(title = 'Strike Rate Analysis',
                   xaxis = {'title':'Strike Rate'},
                   yaxis = {'title':'Player Count'})
fig = go.Figure(data = data, layout = layout)
fig.show()

In [ ]:
# plot Heatmap

six = delivery[delivery['batsman_runs']==6]
six = six.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()
six

            batting_team  over  batsman_runs
0    Chennai Super Kings     1             9
1    Chennai Super Kings     2            21
2    Chennai Super Kings     3            49
3    Chennai Super Kings     4            45
4    Chennai Super Kings     5            53
..                   ...   ...           ...
290  Sunrisers Hyderabad    16            31
291  Sunrisers Hyderabad    17            25
292  Sunrisers Hyderabad    18            49
293  Sunrisers Hyderabad    19            58
294  Sunrisers Hyderabad    20            44

[295 rows x 3 columns]

In [ ]:
from numpy._core.defchararray import title
# plot Heatmap here

trace = go.Heatmap(x=six['batting_team'],y=six['over'],z=six['batsman_runs'])
data = [trace]
trace = go.Layout(title = 'Six Heatmap')
fig = go.Figure(data = data, layout = trace)
fig.show()

In [ ]:
# side by side Heatmaps
dots = delivery[delivery['batsman_runs']==0]
dots = dots.groupby(['batting_team','over'])['batsman_runs'].count().reset_index()

from plotly.subplots import make_subplots
import plotly.graph_objs as go

trace1 = go.Heatmap(x=six['batting_team'],y=six['over'],z=six['batsman_runs'].values.tolist())
trace2 = go.Heatmap(x=dots['batting_team'],y=dots['over'],z=dots['batsman_runs'].values.tolist())

fig = make_subplots(rows=1,cols=2,subplot_titles=["6's","0's"])
fig.append_trace(trace1,1,1)
fig.append_trace(trace2,1,2)
fig.show()